version: "3.6"
services:
  webservice:
    container_name: AS_webservice_API
    build: 
      context: ./
      dockerfile: ./webservice/Dockerfile
    ports:
      - "8080"
    env_file: ./webservice/.env

  dashboardui:
    container_name: AS_dashboardui_client
    build: 
      context: ./
      dockerfile: ./dashboardui/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - webservice
    volumes:
     - /data/certs:/etc/nginx/certs