###

PUT http://localhost:8080/space/646a192da53257300c2ba458
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJnby1zb2NpYWwuand0Z28uaW8iLCJleHAiOjE2ODQ2Nzg0MzcsImlzcyI6Imp3dGdvLmlvIiwidXNlciI6InRlc3QzQGVtYWlsLmNvbSJ9.HYvfHg_zcfZyTtXHcMUuIPJEQ3wTz6RPSC74pUECGbo

{
    "name": "Changed Company name"
}

### delete space

DELETE http://localhost:8080/space/646a192da53257300c2ba458
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJnby1zb2NpYWwuand0Z28uaW8iLCJleHAiOjE2ODQ2Nzg0MzcsImlzcyI6Imp3dGdvLmlvIiwidXNlciI6InRlc3QzQGVtYWlsLmNvbSJ9.HYvfHg_zcfZyTtXHcMUuIPJEQ3wTz6RPSC74pUECGbo

### 

POST http://localhost:8080/space/646a1ce2024dc26b3d4809d2/file
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJnby1zb2NpYWwuand0Z28uaW8iLCJleHAiOjE2ODQ2NzkzOTMsImlzcyI6Imp3dGdvLmlvIiwidXNlciI6InRlc3QzQGVtYWlsLmNvbSJ9.KOLdRd7svgd1oixZgQmaGqmRFWpHXV4RxjLTJMFO2GQ

{
    "name":"23S1",
    "content":"{\"message\": \"Some JSON content\"}"
}

### 

GET http://localhost:8080/space/646a1ce2024dc26b3d4809d2/file/646a1d3b024dc26b3d4809d5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJnby1zb2NpYWwuand0Z28uaW8iLCJleHAiOjE2ODQ2NzkzOTMsImlzcyI6Imp3dGdvLmlvIiwidXNlciI6InRlc3QzQGVtYWlsLmNvbSJ9.KOLdRd7svgd1oixZgQmaGqmRFWpHXV4RxjLTJMFO2GQ
