name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, edited]
    branches: ["main", "develop"]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the apis Docker image
        run: docker build . --file webservice/Dockerfile --tag my-image-name:$(date +%s)
        
  build-frontend:
    needs: build-backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the frontends Docker image
        run: docker build . --file dashboardui/Dockerfile --tag my-image-name:$(date +%s)
  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    needs: build-frontend
    runs-on: ubuntu-latest
#     environment:
#       name: Add environment name
#       url: Add environment url
    steps:
      - name: ssh and run deploy script
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          password: ${{ secrets.SSH_PASS }}
          script: cd dashboard && git pull https://${{ secrets.GH_NAME }}:${{ secrets.GH_PAT }}@github.com/Agile-tools-SaaS/dashboard.git && bash scripts/run.sh
